// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	notifications "github.com/Confialink/wallet-notifications/rpc/proto/notifications"
	mock "github.com/stretchr/testify/mock"
)

// ClientFactory is an autogenerated mock type for the ClientFactory type
type ClientFactory struct {
	mock.Mock
}

// NewClient provides a mock function with given fields:
func (_m *ClientFactory) NewClient() (notifications.NotificationHandler, error) {
	ret := _m.Called()

	var r0 notifications.NotificationHandler
	if rf, ok := ret.Get(0).(func() notifications.NotificationHandler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(notifications.NotificationHandler)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
