package csv

func getUsersHeader() []string {
	return []string{
		"[User information] Profile Type",
		"[User information] First Name",
		"[User information] Last name",
		"[User information] Username",
		"[User information] Email",
		"[User information] Created",
		"[User information] Company name",
		"[User information] Status",
		"[User information] Date of Birth",
		"[User information] Document type",
		"[User information] Document number",
		"[User information] Country of Residence",
		"[User information] Country of Citizenship",
		"[User information] SMS phone number",
		"[User information] Phone Number",
		"[User information] Home Phone",
		"[User information] Office Phone",
		"[User information] Fax",
		"[User information] Group",
		"[Beneficial owner] Full name",
		"[Beneficial owner] Date of Birth",
		"[Beneficial owner] Document type",
		"[Beneficial owner] Document number",
		"[Beneficial owner] Relationship",
		"[Beneficial owner] Address",
		"[Beneficial owner] Phone Number",
		"[Physical address] Address",
		"[Physical address] Address (2nd Line)",
		"[Physical address] City",
		"[Physical address] State/Province/Region",
		"[Physical address] Zip/Postal Code",
		"[Physical address] Country",
		"[Mailing Address] Same as physical",
		"[Mailing Address] Name",
		"[Mailing Address] Address",
		"[Mailing Address] Address (2nd Line)",
		"[Mailing Address] City",
		"[Mailing Address] State/Province/Region",
		"[Mailing Address] Zip/Postal Code",
		"[Mailing Address] Country",
		"[Mailing Address] Phone Number",
		"[Other] Internal Notes",
	}
}
