// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// TokenTTLResolver is an autogenerated mock type for the TokenTTLResolver type
type TokenTTLResolver struct {
	mock.Mock
}

// ResolveByTokenSubject provides a mock function with given fields: subject
func (_m *TokenTTLResolver) ResolveByTokenSubject(subject string) (time.Duration, error) {
	ret := _m.Called(subject)

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(string) time.Duration); ok {
		r0 = rf(subject)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(subject)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
