// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	settings "github.com/Confialink/wallet-settings/rpc/proto/settings"
	mock "github.com/stretchr/testify/mock"
)

// ClientFactory is an autogenerated mock type for the ClientFactory type
type ClientFactory struct {
	mock.Mock
}

// NewClient provides a mock function with given fields:
func (_m *ClientFactory) NewClient() (settings.SettingsHandler, error) {
	ret := _m.Called()

	var r0 settings.SettingsHandler
	if rf, ok := ret.Get(0).(func() settings.SettingsHandler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(settings.SettingsHandler)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
